config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :session_logins
  resources :favorites, only: [:index, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :session_login
end

app/models/session_login.rb
class SessionLogin < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :session_logins
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = current_user.favorites
  end
  def create
    favorite = current_user.favorites.create(session_login_id: params[:session_login_id])
    redirect_to session_logins_path, notice: "#{favorite.session_login.user.name}さんのブログをお気に入り登録しました"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to session_logins_path, notice: "#{favorite.session_login.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/session_logins_controller.rb
class SessionLoginsController < ApplicationController
  before_action :set_session_login, only: %i[ show edit update destroy ]

  # GET /session_logins or /session_logins.json
  def index
    @session_logins = SessionLogin.all
  end

  # GET /session_logins/1 or /session_logins/1.json
  def show
    @favorite = current_user.favorites.find_by(session_login_id: @session_login.id)
  end

  # GET /session_logins/new
  def new
    @session_login = SessionLogin.new
  end

  # GET /session_logins/1/edit
  def edit
  end

  # POST /session_logins or /session_logins.json
  def create
    @session_login = current_user.session_logins.build(session_login_params)
    respond_to do |format|
      if @session_login.save
        format.html { redirect_to @session_login, notice: "Session login was successfully created." }
        format.json { render :show, status: :created, location: @session_login }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @session_login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /session_logins/1 or /session_logins/1.json
  def update
    respond_to do |format|
      if @session_login.update(session_login_params)
        format.html { redirect_to @session_login, notice: "Session login was successfully updated." }
        format.json { render :show, status: :ok, location: @session_login }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @session_login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /session_logins/1 or /session_logins/1.json
  def destroy
    @session_login.destroy
    respond_to do |format|
      format.html { redirect_to session_logins_url, notice: "Session login was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_session_login
      @session_login = SessionLogin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def session_login_params
      params.require(:session_login).permit(:title, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  def show
    @user = User.find(params[:id])
    @favorites = current_user.favorites
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/session_logins_helper.rb
module SessionLoginsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<h1 class="title">お気に入り</h1>
<table>
  <tr>
    <th>title</th>
    <th>content</th>
  </tr>
  <% @favorites.each do |favorite| %>
  <tr>
    <td><%= favorite.session_login.user.name %></td>
    <td><%= favorite.session_login.content %></td>
    </tr>
  <% end %>
</table>
<div><%= link_to "投稿一覧へ", session_logins_path %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
      <%= link_to "Blog", session_logins_path %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/session_logins/_form.html.erb
<%= form_with(model: session_login, local: true) do |form| %>
  <% if session_login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(session_login.errors.count, "error") %> prohibited this session_login from being saved:</h2>

      <ul>
      <% session_login.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/session_logins/edit.html.erb
<h1>Editing Session Login</h1>

<%= render 'form', session_login: @session_login %>

<%= link_to 'Show', @session_login %> |
<%= link_to 'Back', session_logins_path %>

app/views/session_logins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Session Logins</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @session_logins.each do |session_login| %>
      <tr>
        <td><%= session_login.title %></td>
        <td><%= session_login.content %></td>
        <td><%= link_to 'Show', session_login %></td>
        <td><%= link_to 'Edit', edit_session_login_path(session_login) %></td>
        <td><%= link_to 'Destroy', session_login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Session Login', new_session_login_path %>

app/views/session_logins/new.html.erb
<h1>New Session Login</h1>

<%= render 'form', session_login: @session_login %>

<%= link_to 'Back', session_logins_path %>

app/views/session_logins/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @session_login.title %>
</p>
<p>
  <strong>Content:</strong>
  <%= @session_login.content %>
</p>
<% unless @session_login.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(session_login_id: @session_login.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<%= link_to 'favorites',favorites_path %>
<%= link_to 'Edit', edit_session_login_path(@session_login) %>
<%= link_to 'Back', session_logins_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br><br>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>